apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alpha.yaml
  - bravo.yaml

#labels:
#  - pairs:
#      atmos.guidewire.com/cluster-component: "true"

commonLabels:
  someName: someValue
  owner: alice
  app: bingo

generatorOptions:
  # labels to add to all generated resources
  labels:
    additional-label-1: value1
    additional-label-2: value2

#transformers:
#  - label-patch.yaml

#spec:
#  commonMetadata:
#    additional-label-1: value1
#    additional-label-2: value2
#patchesStrategicMerge:
#  - label-patch.yaml
