apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  someName: someValue
  owner: alice
  app: bingo

#labels:
#  - includeSelectors: true
#    pairs:
#      additional-label-1: value1
#  - includeSelectors: false
#    pairs:
#      additional-label-2: value2

resources:
  - alpha.yaml
  - bravo.yaml

#labels:
#  - pairs:
#      atmos.guidewire.com/cluster-component: "true"

#generatorOptions:
#  # labels to add to all generated resources
#  labels:
#    additional-label-1: value1
#    additional-label-2: value2

transformers:
  - label-patch.yaml

#spec:
#  commonMetadata:
#    additional-label-1: value1
#    additional-label-2: value2
#patchesStrategicMerge:
#  - label-patch.yaml
