apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - alpha.yaml
  - bravo.yaml

labels:
  - pairs:
      atmos.guidewire.com/cluster-component: "true"

spec:
  commonMetadata:
    additional-label-1: value1
    additional-label-2: value2
#patchesStrategicMerge:
#  - label-patch.yaml
