#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    additional-label-1: value1
#    additional-label-2: value2
#  name: .*

apiVersion: builtin
kind: LabelTransformer
metadata:
  name: add-or-modify-labels
labels:
  "new-label-1": "value12"
  "new-label-2": "value122"
fieldSpecs:
  - path: metadata/labels
    create: true
#fieldSpecs:
#  - path: metadata/labels
#    create: true
#  - kind: Deployment
#    path: spec/template/metadata/labels
#    create: true
